config/routes.rb
Rails.application.routes.draw do


  get 'events/new'

  get 'events/create'

  get 'events/show'

root 'static_pages#home', as: 'home'
get    '/login',   to: 'sessions#new'
post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'
get  '/signup',  to: 'users#new'
post '/signup',  to: 'users#create'
get 'sessions/new'

resources :users
resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_and_belongs_to_many :attendees, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
 has_many :created_events, foreign_key: "creator_id", class_name: "Event"

 has_and_belongs_to_many :attended_events, class_name: "Event"


 before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { in: 4..20}, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @event = Event.all
    @user = current_user
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.new(event_params)
    if @event.save
      flash.now[:success] = "Votre evenement a ete ajoute"
      redirect_to events_path
      @event.attendees << current_user
      @event.save
    else
      render 'new'
      flash.now[:error] = "L'événement n'a pas été créé"
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all
  end

  private
      def event_params
        params.require(:event).permit(:description, :date, :place)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/name combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to home_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  if @user.save
    log_in @user
    flash.now[:success] = "Sign up complete !"
    redirect_to @user
  else
    render 'new'
  end
  end

  def show
    @user = User.find(params[:id])
  end

  private
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
@current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% provide(:title, 'Evenements a venir') %>
  <% if logged_in? %>

        <h1>Evenements</h1>

        <table>
         <tr>
           <th><h3>|Description</h3></th>
           <th><h3>|Date</h3></th>
           <th><h3>|Lieu</h3></th>
           <th><h3>|Proposé par</h3></th>
           <th>|</th>
         </tr>

        <% @event.each do |event| %>
           <tr>
             <td>| <%= event.description %> </td>
             <td>| <%= event.date %> </td>
             <td>| <%= event.place %> </td>
             <td>| <%= event.creator.name %> </td>
             <td>| </td>
              <% end %>
           </tr>
          </table>
          <h3><%= link_to "Propose un événement",  new_event_path %></h3>
          <% else %>
<h3>Rejoins-nous pour Proposer ou Participer a un événement</h3>
 <% end %>

app/views/events/new.html.erb
<% provide(:title, 'Event') %>
  <% if logged_in? %>
<h1>Propose ton événement</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
   <%= form_for Event.new do |f| %>
     <%= render 'shared/error_message_event' %>

     <%= f.label :description %>
     <%= f.text_area :description, class: 'form-control' %>
     <br/>
     <%= f.label :date %>
     <%= f.datetime_select :date, class: 'form-control' %>
     <br/>
     <%= f.label :lieu %>
     <%= f.text_field :place, class: 'form-control' %>
     <br/>
     <%= f.submit "Créer mon evenement", class: "btn btn-primary" %>
   <% end %>
 </div>
</div>
<% else %>
<h3>Rejoins-nous pour Proposer ou Participer a un événement</h3>
 <% end %>

app/views/events/show.html.erb
<% provide(:title, @user.email) %>
  <% if logged_in? %>
<h1>
  <%= @user.name %>
</h1>

<p>
  <%= @user.email %>
</p>
<%= link_to "Propose un evenement",  new_event_path %>
<% else %>
<h3>Rejoins-nous pour Proposer ou Participer a un evenement</h3>
 <% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
 <a id="logo" href="/">P & P Evenements</a>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Evenements",   events_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Profil <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profil", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to "Deconnexion", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Connnexion", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P & P Evenements</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message_event.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Propose & Participe</h1>
  <% if logged_in? %>
  <p><%= link_to "Evenements", events_path,class: "btn btn-lg btn-primary" %></p>
  <% else %>
  <h3>
    Inscrits-toi pour voir et poster des événements
  </h3>
  <p><%= link_to "Inscription", new_user_path,class: "btn btn-lg btn-primary" %></p>
    <p>Deja inscrit ? <%= link_to "Log in", '/login' %></p>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Inscription</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Inscription", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
  <% if logged_in? %>
<h1>
  <%= @user.name %>
</h1>

<p>
  email : <%= @user.email %>
</p>

<h1>Tes événement</h1>

<table>
 <tr>
   <th><h3>|Description</h3></th>
   <th><h3>|Date</h3></th>
   <th><h3>|Lieu</h3></th>
   <th><h3>|Proposé par</h3></th>
   <th>|</th>
 </tr>

<% @user.created_events.each do |event| %>
   <tr>
     <td>| <%= event.description %> </td>
     <td>| <%= event.date %> </td>
     <td>| <%= event.place %> </td>
     <td>| <%= event.creator.name %> </td>
     <td>| </td>
      <% end %>
   </tr>
  </table>

<h3><%= link_to "Propose un événement",  new_event_path %></h3>
<% end %>